# [Gradle Configuration]

# Allowing parallel computing for multiple modules
org.gradle.parallel=true
# Make use of caching tool to allow much faster build.
org.gradle.caching=true
# Only configure the module that is relevant to the current build, not configuring them all up-front
org.gradle.configureondemand=true